function getUnlockStatus(name) {
  const raw = localStorage.getItem(`wordmastery_${name}`);
  const data = raw ? JSON.parse(raw) : {};
  return data.unlocked || { part2: false, wordbank: false };
}

function setUnlockStatus(name, material, value) {
  const key = `wordmastery_${name}`;
  const raw = localStorage.getItem(key);
  const data = raw ? JSON.parse(raw) : { score: 0, streak: 0, words: {} };
  if (!data.unlocked) data.unlocked = { part2: false, wordbank: false };
  data.unlocked[material] = value;
  localStorage.setItem(key, JSON.stringify(data));
}

const ROSTER = [
  { name: "Emmanuel Ifeanyichukwu", pin: "1024" },
  { name: "Oluoti Mahmud", pin: "3391" },
  { name: "Chantel Christian", pin: "5820" },
  { name: "Charissa Christian", pin: "7146" },
  { name: "Chimdalu Emmanuel", pin: "9053" },
];

const WORDS = [
  {
    id: 500,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 1,
    word: "the",
    ipa: "/ðə/",
  },
  {
    id: 501,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 1,
    word: "the",
    ipa: "/ðiː/",
  },
  {
    id: 502,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 1,
    word: "and",
    ipa: "/ænd/",
  },
  {
    id: 503,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 1,
    word: "and",
    ipa: "/ənd/",
  },
  {
    id: 504,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 1,
    word: "boy",
    ipa: "/bɔɪ/",
  },
  {
    id: 505,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 1,
    word: "girl",
    ipa: "/ɡɜːl/",
  },

  {
    id: 506,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 2,
    word: "to",
    ipa: "/tuː/",
  },
  {
    id: 507,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 2,
    word: "to",
    ipa: "/tə/",
  },
  {
    id: 508,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 2,
    word: "in",
    ipa: "/ɪn/",
  },
  {
    id: 509,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 2,
    word: "is",
    ipa: "/ɪz/",
  },
  {
    id: 510,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 2,
    word: "mother",
    ipa: "/ˈmʌð.əʳ/",
  },
  {
    id: 511,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 2,
    word: "father",
    ipa: "/ˈfɑː.ðəʳ/",
  },

  {
    id: 512,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 3,
    word: "are",
    ipa: "/ɑːʳ/",
  },
  {
    id: 513,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 3,
    word: "are",
    ipa: "/ə/",
  },
  {
    id: 514,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 3,
    word: "you",
    ipa: "/juː/",
  },
  {
    id: 515,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 3,
    word: "of",
    ipa: "/ɒv/",
  },
  {
    id: 516,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 3,
    word: "of",
    ipa: "/əv/",
  },
  {
    id: 517,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 3,
    word: "that",
    ipa: "/ðæt/",
  },
  {
    id: 518,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 3,
    word: "that",
    ipa: "/ðət/",
  },
  {
    id: 519,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 3,
    word: "sister",
    ipa: "/ˈsɪs.təʳ/",
  },
  {
    id: 520,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 3,
    word: "brother",
    ipa: "/ˈbrʌð.əʳ/",
  },

  {
    id: 521,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 4,
    word: "it",
    ipa: "/ɪt/",
  },
  {
    id: 522,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 4,
    word: "he",
    ipa: "/hiː/",
  },
  {
    id: 523,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 4,
    word: "yes",
    ipa: "/jes/",
  },
  {
    id: 524,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 4,
    word: "was",
    ipa: "/wɒz/",
  },
  {
    id: 525,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 4,
    word: "was",
    ipa: "/wəz/",
  },
  {
    id: 526,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 4,
    word: "baby",
    ipa: "/ˈbeɪ.bi/",
  },
  {
    id: 527,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 4,
    word: "friend",
    ipa: "/frend/",
  },
  {
    id: 528,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 4,
    word: "it's",
    ipa: "/ɪts/",
  },
  {
    id: 529,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 4,
    word: "he's",
    ipa: "/hiːz/",
  },

  {
    id: 530,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 5,
    word: "for",
    ipa: "/fɔːʳ/",
  },
  {
    id: 531,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 5,
    word: "for",
    ipa: "/fə/",
  },
  {
    id: 532,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 5,
    word: "on",
    ipa: "/ɒn/",
  },
  {
    id: 533,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 5,
    word: "teacher",
    ipa: "/ˈtiː.tʃəʳ/",
  },
  {
    id: 534,
    material: "part1",
    module: 1,
    unit: 1,
    lesson: 5,
    word: "doctor",
    ipa: "/ˈdɒk.təʳ/",
  },

  {
    id: 535,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 1,
    word: "as",
    ipa: "/æz/",
  },
  {
    id: 536,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 1,
    word: "as",
    ipa: "/əz/",
  },
  {
    id: 537,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 1,
    word: "with",
    ipa: "/wɪð/",
  },
  {
    id: 538,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 1,
    word: "police",
    ipa: "/pəˈliːs/",
  },
  {
    id: 539,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 1,
    word: "fireman",
    ipa: "/ˈfaɪə.mən/",
  },
  {
    id: 540,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 1,
    word: "chef",
    ipa: "/ʃef/",
  },

  {
    id: 541,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 2,
    word: "his",
    ipa: "/hɪz/",
  },
  {
    id: 542,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 2,
    word: "his",
    ipa: "/ɪz/",
  },
  {
    id: 543,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 2,
    word: "they",
    ipa: "/ðeɪ/",
  },
  {
    id: 544,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 2,
    word: "farmer",
    ipa: "/ˈfɑː.məʳ/",
  },
  {
    id: 545,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 2,
    word: "house",
    ipa: "/haʊs/",
  },
  {
    id: 546,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 2,
    word: "room",
    ipa: "/ruːm/",
  },
  {
    id: 547,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 2,
    word: "they're",
    ipa: "/ðeəʳ/",
  },

  {
    id: 548,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 3,
    word: "at",
    ipa: "/æt/",
  },
  {
    id: 549,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 3,
    word: "at",
    ipa: "/ət/",
  },
  {
    id: 550,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 3,
    word: "be",
    ipa: "/biː/",
  },
  {
    id: 551,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 3,
    word: "be",
    ipa: "/bi/",
  },
  {
    id: 552,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 3,
    word: "no",
    ipa: "/nəʊ/",
  },
  {
    id: 553,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 3,
    word: "bed",
    ipa: "/bed/",
  },
  {
    id: 554,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 3,
    word: "chair",
    ipa: "/tʃeəʳ/",
  },
  {
    id: 555,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 3,
    word: "table",
    ipa: "/ˈteɪ.bl̩/",
  },

  {
    id: 556,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 4,
    word: "this",
    ipa: "/ðɪs/",
  },
  {
    id: 557,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 4,
    word: "from",
    ipa: "/frɒm/",
  },
  {
    id: 558,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 4,
    word: "from",
    ipa: "/frəm/",
  },
  {
    id: 559,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 4,
    word: "door",
    ipa: "/dɔːʳ/",
  },
  {
    id: 560,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 4,
    word: "window",
    ipa: "/ˈwɪn.dəʊ/",
  },
  {
    id: 561,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 4,
    word: "book",
    ipa: "/bʊk/",
  },

  {
    id: 562,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 5,
    word: "have",
    ipa: "/hæv/",
  },
  {
    id: 563,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 5,
    word: "have",
    ipa: "/həv/",
  },
  {
    id: 564,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 5,
    word: "pencil",
    ipa: "/ˈpen.səl/",
  },
  {
    id: 565,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 5,
    word: "paper",
    ipa: "/ˈpeɪ.pəʳ/",
  },
  {
    id: 566,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 5,
    word: "toy",
    ipa: "/tɔɪ/",
  },
  {
    id: 567,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 5,
    word: "I'm",
    ipa: "/aɪm/",
  },
  {
    id: 568,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 5,
    word: "you've",
    ipa: "/juːv/",
  },
  {
    id: 569,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 5,
    word: "they've",
    ipa: "/ðeɪv/",
  },
  {
    id: 570,
    material: "part1",
    module: 1,
    unit: 2,
    lesson: 5,
    word: "I've",
    ipa: "/aɪv/",
  },

  {
    id: 571,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "or",
    ipa: "/ɔːʳ/",
  },
  {
    id: 572,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "or",
    ipa: "/ə/",
  },
  {
    id: 573,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "one",
    ipa: "/wʌn/",
  },
  {
    id: 574,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "had",
    ipa: "/hæd/",
  },
  {
    id: 575,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "had",
    ipa: "/həd/",
  },
  {
    id: 576,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "had",
    ipa: "/əd/",
  },
  {
    id: 577,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "by",
    ipa: "/baɪ/",
  },
  {
    id: 578,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "ball",
    ipa: "/bɔːl/",
  },
  {
    id: 579,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "clock",
    ipa: "/klɒk/",
  },
  {
    id: 580,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "lamp",
    ipa: "/læmp/",
  },
  {
    id: 581,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "zero",
    ipa: "/ˈzɪə.rəʊ/",
  },
  {
    id: 582,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "you'd",
    ipa: "/juːd/",
  },
  {
    id: 583,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "they'd",
    ipa: "/ðeɪd/",
  },
  {
    id: 584,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "he'd",
    ipa: "/hiːd/",
  },
  {
    id: 585,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "it'd",
    ipa: "/ˈɪt.əd/",
  },
  {
    id: 586,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 1,
    word: "I'd",
    ipa: "/aɪd/",
  },

  {
    id: 587,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "word",
    ipa: "/wɜːd/",
  },
  {
    id: 588,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "but",
    ipa: "/bʌt/",
  },
  {
    id: 589,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "but",
    ipa: "/bət/",
  },
  {
    id: 590,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "not",
    ipa: "/nɒt/",
  },
  {
    id: 591,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "what",
    ipa: "/wɒt/",
  },
  {
    id: 592,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "food",
    ipa: "/fuːd/",
  },
  {
    id: 593,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "drink",
    ipa: "/drɪŋk/",
  },
  {
    id: 594,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "spoon",
    ipa: "/spuːn/",
  },
  {
    id: 595,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "two",
    ipa: "/tuː/",
  },
  {
    id: 596,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "isn't",
    ipa: "/ˈɪz.ənt/",
  },
  {
    id: 597,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "aren't",
    ipa: "/ɑːnt/",
  },
  {
    id: 598,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "wasn't",
    ipa: "/ˈwɒz.ənt/",
  },
  {
    id: 599,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "haven't",
    ipa: "/ˈhæv.ənt/",
  },
  {
    id: 600,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 2,
    word: "hadn't",
    ipa: "/ˈhæd.ənt/",
  },

  {
    id: 601,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "all",
    ipa: "/ɔːl/",
  },
  {
    id: 602,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "were",
    ipa: "/wɜːʳ/",
  },
  {
    id: 603,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "were",
    ipa: "/wə/",
  },
  {
    id: 604,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "we",
    ipa: "/wiː/",
  },
  {
    id: 605,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "we",
    ipa: "/wi/",
  },
  {
    id: 606,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "when",
    ipa: "/wen/",
  },
  {
    id: 607,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "fork",
    ipa: "/fɔːk/",
  },
  {
    id: 608,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "plate",
    ipa: "/pleɪt/",
  },
  {
    id: 609,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "cup",
    ipa: "/kʌp/",
  },
  {
    id: 610,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "three",
    ipa: "/θriː/",
  },
  {
    id: 611,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "we're",
    ipa: "/wɪəʳ/",
  },
  {
    id: 612,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "we've",
    ipa: "/wiːv/",
  },
  {
    id: 613,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "we'd",
    ipa: "/wiːd/",
  },
  {
    id: 614,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 3,
    word: "weren't",
    ipa: "/wɜːnt/",
  },

  {
    id: 615,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "your",
    ipa: "/jɔːʳ/",
  },
  {
    id: 616,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "your",
    ipa: "/jə/",
  },
  {
    id: 617,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "can",
    ipa: "/kæn/",
  },
  {
    id: 618,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "can",
    ipa: "/kən/",
  },
  {
    id: 619,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "said",
    ipa: "/sed/",
  },
  {
    id: 620,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "there",
    ipa: "/ðeəʳ/",
  },
  {
    id: 621,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "there",
    ipa: "/ðə/",
  },
  {
    id: 622,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "phone",
    ipa: "/fəʊn/",
  },
  {
    id: 623,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "box",
    ipa: "/bɒks/",
  },
  {
    id: 624,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "car",
    ipa: "/kɑːʳ/",
  },
  {
    id: 625,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "four",
    ipa: "/fɔːʳ/",
  },
  {
    id: 626,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "yours",
    ipa: "/jɔːz/",
  },
  {
    id: 627,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "there's",
    ipa: "/ðeəz/",
  },
  {
    id: 628,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "there're",
    ipa: "/ðeər.ə/",
  },
  {
    id: 629,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "can't",
    ipa: "/kɑːnt/",
  },
  {
    id: 630,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 4,
    word: "you're",
    ipa: "/jɔːʳ/",
  },

  {
    id: 631,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "use",
    ipa: "/juːz/",
  },
  {
    id: 632,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "use",
    ipa: "/juːs/",
  },
  {
    id: 633,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "an",
    ipa: "/æn/",
  },
  {
    id: 634,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "an",
    ipa: "/ən/",
  },
  {
    id: 635,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "old",
    ipa: "/əʊld/",
  },
  {
    id: 636,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "each",
    ipa: "/iːtʃ/",
  },
  {
    id: 637,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "which",
    ipa: "/wɪtʃ/",
  },
  {
    id: 638,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "bike",
    ipa: "/baɪk/",
  },
  {
    id: 639,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "shoe",
    ipa: "/ʃuː/",
  },
  {
    id: 640,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "hat",
    ipa: "/hæt/",
  },
  {
    id: 641,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "five",
    ipa: "/faɪv/",
  },
  {
    id: 642,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "uses",
    ipa: "/ˈjuː.zɪz/",
  },
  {
    id: 643,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "uses",
    ipa: "/ˈjuː.sɪz/",
  },
  {
    id: 644,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "used",
    ipa: "/juːzd/",
  },
  {
    id: 645,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "used",
    ipa: "/juːst/",
  },
  {
    id: 646,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "using",
    ipa: "/ˈjuː.zɪŋ/",
  },
  {
    id: 647,
    material: "part1",
    module: 2,
    unit: 1,
    lesson: 5,
    word: "being",
    ipa: "/ˈbiː.ɪŋ/",
  },

  {
    id: 648,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "she",
    ipa: "/ʃiː/",
  },
  {
    id: 649,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "she",
    ipa: "/ʃi/",
  },
  {
    id: 650,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "do",
    ipa: "/duː/",
  },
  {
    id: 651,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "do",
    ipa: "/du/",
  },
  {
    id: 652,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "do",
    ipa: "/də/",
  },
  {
    id: 653,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "how",
    ipa: "/haʊ/",
  },
  {
    id: 654,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "their",
    ipa: "/ðeəʳ/",
  },
  {
    id: 655,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "dress",
    ipa: "/dres/",
  },
  {
    id: 656,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "coat",
    ipa: "/kəʊt/",
  },
  {
    id: 657,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "floor",
    ipa: "/flɔːʳ/",
  },
  {
    id: 658,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "plus",
    ipa: "/plʌs/",
  },
  {
    id: 659,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "add",
    ipa: "/æd/",
  },
  {
    id: 660,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "theirs",
    ipa: "/ðeəz/",
  },
  {
    id: 661,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "don't",
    ipa: "/dəʊnt/",
  },
  {
    id: 662,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "doesn't",
    ipa: "/ˈdʌz.ənt/",
  },
  {
    id: 663,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "she'd",
    ipa: "/ʃiːd/",
  },
  {
    id: 664,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "dressing",
    ipa: "/ˈdres.ɪŋ/",
  },
  {
    id: 665,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "doing",
    ipa: "/ˈduː.ɪŋ/",
  },
  {
    id: 666,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "dresses",
    ipa: "/ˈdres.ɪz/",
  },
  {
    id: 667,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 1,
    word: "dressed",
    ipa: "/drest/",
  },

  {
    id: 668,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "if",
    ipa: "/ɪf/",
  },
  {
    id: 669,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "will",
    ipa: "/wɪl/",
  },
  {
    id: 670,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "will",
    ipa: "/əl/",
  },
  {
    id: 671,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "up",
    ipa: "/ʌp/",
  },
  {
    id: 672,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "other",
    ipa: "/ˈʌð.əʳ/",
  },
  {
    id: 673,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "wall",
    ipa: "/wɔːl/",
  },
  {
    id: 674,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "cat",
    ipa: "/kæt/",
  },
  {
    id: 675,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "dog",
    ipa: "/dɒɡ/",
  },
  {
    id: 676,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "six",
    ipa: "/sɪks/",
  },
  {
    id: 677,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "equal",
    ipa: "/ˈiː.kwəl/",
  },
  {
    id: 678,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "others",
    ipa: "/ˈʌð.əz/",
  },
  {
    id: 679,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "won't",
    ipa: "/wəʊnt/",
  },
  {
    id: 680,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "you'll",
    ipa: "/juːl/",
  },
  {
    id: 681,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "that'll",
    ipa: "/ˈðæt.əl/",
  },
  {
    id: 682,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "it'll",
    ipa: "/ˈɪt.əl/",
  },
  {
    id: 683,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "he'll",
    ipa: "/hiːl/",
  },
  {
    id: 684,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "they'll",
    ipa: "/ðeɪl/",
  },
  {
    id: 685,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "I'll",
    ipa: "/aɪl/",
  },
  {
    id: 686,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "we'll",
    ipa: "/wiːl/",
  },
  {
    id: 687,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 2,
    word: "there'll",
    ipa: "/ðeə.l/",
  },

  {
    id: 688,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "about",
    ipa: "/əˈbaʊt/",
  },
  {
    id: 689,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "out",
    ipa: "/aʊt/",
  },
  {
    id: 690,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "many",
    ipa: "/ˈmen.i/",
  },
  {
    id: 691,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "then",
    ipa: "/ðen/",
  },
  {
    id: 692,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "bird",
    ipa: "/bɜːd/",
  },
  {
    id: 693,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "fish",
    ipa: "/fɪʃ/",
  },
  {
    id: 694,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "cow",
    ipa: "/kaʊ/",
  },
  {
    id: 695,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "seven",
    ipa: "/ˈsev.ən/",
  },
  {
    id: 696,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "fished",
    ipa: "/fɪʃt/",
  },
  {
    id: 697,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "using",
    ipa: "/ˈjuː.zɪŋ/",
  },
  {
    id: 698,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "being",
    ipa: "/ˈbiː.ɪŋ/",
  },
  {
    id: 699,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "dressing",
    ipa: "/ˈdres.ɪŋ/",
  },
  {
    id: 700,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "doing",
    ipa: "/ˈduː.ɪŋ/",
  },
  {
    id: 701,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 3,
    word: "fishing",
    ipa: "/ˈfɪʃ.ɪŋ/",
  },

  {
    id: 702,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 4,
    word: "them",
    ipa: "/ðem/",
  },
  {
    id: 703,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 4,
    word: "them",
    ipa: "/ðəm/",
  },
  {
    id: 704,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 4,
    word: "these",
    ipa: "/ðiːz/",
  },
  {
    id: 705,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 4,
    word: "so",
    ipa: "/səʊ/",
  },
  {
    id: 706,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 4,
    word: "some",
    ipa: "/sʌm/",
  },
  {
    id: 707,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 4,
    word: "some",
    ipa: "/səm/",
  },
  {
    id: 708,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 4,
    word: "pig",
    ipa: "/pɪɡ/",
  },
  {
    id: 709,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 4,
    word: "horse",
    ipa: "/hɔːs/",
  },
  {
    id: 710,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 4,
    word: "duck",
    ipa: "/dʌk/",
  },
  {
    id: 711,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 4,
    word: "eight",
    ipa: "/eɪt/",
  },

  {
    id: 712,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "her",
    ipa: "/hɜːʳ/",
  },
  {
    id: 713,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "her",
    ipa: "/hə/",
  },
  {
    id: 714,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "her",
    ipa: "/ə/",
  },
  {
    id: 715,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "would",
    ipa: "/wʊd/",
  },
  {
    id: 716,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "would",
    ipa: "/wəd/",
  },
  {
    id: 717,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "make",
    ipa: "/meɪk/",
  },
  {
    id: 718,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "like",
    ipa: "/laɪk/",
  },
  {
    id: 719,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "sheep",
    ipa: "/ʃiːp/",
  },
  {
    id: 720,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "snake",
    ipa: "/sneɪk/",
  },
  {
    id: 721,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "jump",
    ipa: "/dʒʌmp/",
  },
  {
    id: 722,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "nine",
    ipa: "/naɪn/",
  },
  {
    id: 723,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "hers",
    ipa: "/hɜːz/",
  },
  {
    id: 724,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "liked",
    ipa: "/laɪkt/",
  },
  {
    id: 725,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "jumped",
    ipa: "/dʒʌmpt/",
  },
  {
    id: 726,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "making",
    ipa: "/ˈmeɪ.kɪŋ/",
  },
  {
    id: 727,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "liking",
    ipa: "/ˈlaɪ.kɪŋ/",
  },
  {
    id: 728,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "jumping",
    ipa: "/ˈdʒʌm.pɪŋ/",
  },
  {
    id: 729,
    material: "part1",
    module: 2,
    unit: 2,
    lesson: 5,
    word: "wouldn't",
    ipa: "/ˈwʊd.ənt/",
  },
];

const MATERIAL_LABELS = {
  part1: {
    title: "Part 1",
    subtitle: "Foundation decoding words",
    cls: "part1",
  },
  part2: {
    title: "Part 2",
    subtitle: "Advanced decoding words",
    cls: "part2",
  },
  wordbank: {
    title: "Word Bank",
    subtitle: "Common words by subject",
    cls: "wordbank",
  },
};

function getCustomWords() {
  return JSON.parse(localStorage.getItem("customWords") || "[]");
}

function saveCustomWords(words) {
  localStorage.setItem("customWords", JSON.stringify(words));
}

function getAllWords() {
  return [...WORDS, ...getCustomWords()];
}

function addCustomWord(wordObj) {
  const custom = getCustomWords();
  wordObj.id = 1000 + custom.length;
  custom.push(wordObj);
  saveCustomWords(custom);
}
